
// Fix: Removing unused and invalid import 'PastMatch' to resolve compilation error
import { Player, Match } from './types.ts';

export const MASTER_ADMIN_EMAIL = 'diiogo49@gmail.com';

export const MAIN_LOGO_URL = "https://i.postimg.cc/QCGV109g/Gemini-Generated-Image-xrrv8axrrv8axrrv-removebg-preview.png";

export const MAINTENANCE_MASCOTS_IMG = "/images/maintenance_mascots.jpg";

export const MOCK_PLAYERS: Player[] = [
  {
    id: 'p-1',
    name: 'Diogo Silva (Admin)',
    email: 'diiogo49@gmail.com',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    number: 10,
    goals: 28,
    assists: 14,
    concededGoals: 0,
    totalGames: 16,
    totalWins: 13,
    position: 'Meio-Campo',
    status: 'presente',
    confirmedAt: '2026-02-15T18:00:00Z',
    playerType: 'mensalista',
    role: 'admin',
    monthlyPaid: true,
    paymentStatus: 'pago',
    pushEnabled: true
  },
  {
    id: 'p-2',
    name: 'Lucas Arcanjo',
    email: 'lucas.gk@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    number: 1,
    goals: 1,
    assists: 3,
    concededGoals: 8,
    totalGames: 15,
    totalWins: 11,
    position: 'Goleiro',
    status: 'presente',
    confirmedAt: '2026-02-15T18:05:00Z',
    playerType: 'mensalista',
    role: 'player',
    monthlyPaid: true,
    paymentStatus: 'pago'
  },
  {
    id: 'p-3',
    name: 'Gabriel Barbosa',
    email: 'gabigol@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    number: 9,
    goals: 24,
    assists: 8,
    concededGoals: 0,
    totalGames: 14,
    totalWins: 10,
    position: 'Atacante',
    status: 'presente',
    confirmedAt: '2026-02-15T18:10:00Z',
    playerType: 'mensalista',
    role: 'player',
    monthlyPaid: true,
    paymentStatus: 'pago'
  },
  {
    id: 'p-4',
    name: 'Matheus Muralha',
    email: 'muralha@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    number: 12,
    goals: 0,
    assists: 1,
    concededGoals: 12,
    totalGames: 14,
    totalWins: 9,
    position: 'Goleiro',
    status: 'presente',
    confirmedAt: '2026-02-15T18:12:00Z',
    playerType: 'avulso',
    role: 'player',
    monthlyPaid: false,
    paymentStatus: 'pago'
  },
  {
    id: 'p-5',
    name: 'Rodrigo Caio',
    email: 'rodrigo@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    number: 3,
    goals: 8,
    assists: 5,
    concededGoals: 0,
    totalGames: 13,
    totalWins: 8,
    position: 'Zagueiro',
    status: 'presente',
    confirmedAt: '2026-02-15T18:15:00Z',
    playerType: 'mensalista',
    role: 'player',
    monthlyPaid: true,
    paymentStatus: 'pago'
  },
  {
    id: 'p-6',
    name: 'Felipe Luva de Ouro',
    email: 'felipe.gk@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    number: 22,
    goals: 0,
    assists: 2,
    concededGoals: 10,
    totalGames: 12,
    totalWins: 7,
    position: 'Goleiro',
    status: 'presente',
    confirmedAt: '2026-02-15T18:16:00Z',
    playerType: 'mensalista',
    role: 'player',
    monthlyPaid: true,
    paymentStatus: 'pago'
  },
  {
    id: 'p-7',
    name: 'Vitor Roque',
    email: 'vitor@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    number: 11,
    goals: 19,
    assists: 9,
    concededGoals: 0,
    totalGames: 12,
    totalWins: 8,
    position: 'Atacante',
    status: 'presente',
    confirmedAt: '2026-02-15T18:20:00Z',
    playerType: 'avulso',
    role: 'player',
    monthlyPaid: false,
    paymentStatus: 'pendente'
  },
  {
    id: 'p-8',
    name: 'Renan Paredão',
    email: 'renan.gk@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
    number: 25,
    goals: 0,
    assists: 0,
    concededGoals: 14,
    totalGames: 10,
    totalWins: 6,
    position: 'Goleiro',
    status: 'presente',
    confirmedAt: '2026-02-15T18:22:00Z',
    playerType: 'mensalista',
    role: 'player',
    monthlyPaid: true,
    paymentStatus: 'pago'
  },
  {
    id: 'p-9',
    name: 'Bruno Guimarães',
    email: 'bruno@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    number: 8,
    goals: 14,
    assists: 16,
    concededGoals: 0,
    totalGames: 11,
    totalWins: 8,
    position: 'Meio-Campo',
    status: 'presente',
    confirmedAt: '2026-02-15T18:25:00Z',
    playerType: 'mensalista',
    role: 'player',
    monthlyPaid: true,
    paymentStatus: 'pago'
  },
  {
    id: 'p-10',
    name: 'Diego Gatão',
    email: 'diego.gk@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    number: 31,
    goals: 0,
    assists: 1,
    concededGoals: 9,
    totalGames: 9,
    totalWins: 6,
    position: 'Goleiro',
    status: 'presente',
    confirmedAt: '2026-02-15T18:30:00Z',
    playerType: 'avulso',
    role: 'player',
    monthlyPaid: false,
    paymentStatus: 'pago'
  },
  {
    id: 'p-11',
    name: 'Pedro Geromel',
    email: 'geromel@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150',
    number: 4,
    goals: 5,
    assists: 3,
    concededGoals: 0,
    totalGames: 10,
    totalWins: 7,
    position: 'Zagueiro',
    status: 'presente',
    confirmedAt: '2026-02-15T18:35:00Z',
    playerType: 'mensalista',
    role: 'player',
    monthlyPaid: true,
    paymentStatus: 'pago'
  },
  {
    id: 'p-12',
    name: 'Everton Cebolinha',
    email: 'cebolinha@ousadia.app',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
    number: 7,
    goals: 16,
    assists: 11,
    concededGoals: 0,
    totalGames: 10,
    totalWins: 7,
    position: 'Atacante',
    status: 'pendente',
    playerType: 'avulso',
    role: 'player',
    monthlyPaid: false,
    paymentStatus: 'pendente'
  }
];

export const CURRENT_MATCH: Match = {
  id: 'match-2026-feb',
  location: 'Granja Cantinho do Céu',
  date: '2026-02-15',
  time: '20:00',
  type: 'Society',
  price: 40.00,
  confirmedPlayers: 18,
  fieldSlots: 30,
  gkSlots: 4,
  createdAt: '2026-02-01T10:00:00Z'
};
